version: "3.9"

services:
  web:
    build:
      context: .
      dockerfile: ./docker/php/Dockerfile
      args:
        ENV: development
    # restart: always
    volumes:
      - ./docker/php/php.ini:/usr/local/etc/php/php.ini
      - ./web:/var/www/html/
    working_dir: /var/www/html/
    ports:
      - ${WEB_PORT}:80
    depends_on:
      - mysql

  mysql:
    image: mysql:8.0.30
    # restart: always
    ports:
      - ${MYSQL_PORT}:3306
    command:
      - --sql-mode=NO_ENGINE_SUBSTITUTION
      - --default-authentication-plugin=mysql_native_password
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    env_file:
      - ./docker/config/dev.env
    environment:
      - BIND-ADDRESS=0.0.0.0
      - TZ=Asia/Tokyo
    volumes:
      - ./data:/var/lib/mysql
      - ./docker/mysql/my.cnf:/etc/mysql/conf.d/my.cnf
      - ./schema:/var/tmp
    working_dir: /var/tmp

  cron:
    build:
      context: .
      dockerfile: ./docker/cron/Dockerfile
    volumes:
      - ./docker/cron/crontab:/etc/crontabs/root
      - ./web:/var/www/html
